version: 2
build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-22.9
  jobs:
    pre_build:
      - doit list
      - doit bootstrap
      - doit list
      - doit build:source_date_epoch
      - doit build
      - doit list
      - doit lite
      - doit list
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
conda:
  environment: docs/environment.yml
