"$id" = "https://doitoml.rtfd.io/en/latest/schema/v1.schema.json"
"$ref" = "#/definitions/config"
"$schema" = "http://json-schema.org/draft-07/schema#"

[definitions.config]
description = "schema for ``doitoml`` configuration"
type = "object"
required = ["tasks", "cmd", "env", "paths"]

[definitions.config.properties]
tasks = {"$ref" = "#/definitions/tasks", description = "named tasks"}
cmd = {"$ref" = "#/definitions/cmd", description = "named command tokens"}
env = {"$ref" = "#/definitions/env", description = "environment variables"}
paths = {"$ref" = "#/definitions/paths", description = "named paths"}

[definitions.array-of-strings]
type = "array"
items = {type = "string"}

[definitions.tasks.patternProperties.'[^=\s]+']
"$ref" = "#/definitions/task"

[definitions.task]
type = "object"

[definitions.cmd]
type = "object"
additionalProperties = {"$ref" = "#/definitions/array-of-strings"}

[definitions.env]
type = "object"
additionalProperties = {type = "string"}

[definitions.paths]
type = "object"
additionalProperties = {"$ref" = "#/definitions/array-of-strings"}
