[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "b"
description = "b"
version = "0.0.0"
authors = [
    {name = "doitoml", email = "doitoml@example.com"},
]
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: MIT License",
]
